/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tax.calculation.system;

/**
 *
 * @author Divyanshu jain
 */
public class co_orperative extends javax.swing.JFrame {

    /**
     * Creates new form co_orperative
     */
    public co_orperative() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cp = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        mat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ddt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        dop = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Co-orperative Tax ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 11, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Co-orperativeName");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 139, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Source of Income");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 176, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Department");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 213, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 174, 207, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 211, 207, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 137, 206, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 174, 206, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 211, 206, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bank A/C No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 213, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 176, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Pan no.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 139, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Cost of Production");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 254, -1, -1));

        cp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });
        cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cpKeyReleased(evt);
            }
        });
        getContentPane().add(cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 251, 147, 28));

        p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        p.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pKeyReleased(evt);
            }
        });
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 297, 147, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Profit");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 299, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Deduction On Gross Turnover");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 334, -1, 33));

        gt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        gt.setPreferredSize(new java.awt.Dimension(106, 28));
        gt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gtActionPerformed(evt);
            }
        });
        getContentPane().add(gt, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 336, 147, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Including surcharge Tax and health and education cess");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 454, -1, 36));

        mat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        mat.setPreferredSize(new java.awt.Dimension(106, 28));
        mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matActionPerformed(evt);
            }
        });
        getContentPane().add(mat, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 417, 147, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Divident Distribution Tax(DDT)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 543, -1, 33));

        ddt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ddt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ddt.setPreferredSize(new java.awt.Dimension(106, 28));
        ddt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddtActionPerformed(evt);
            }
        });
        getContentPane().add(ddt, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 545, 147, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Minimum Alternative Tax(MAT)");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 415, -1, 33));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("(Including surcharge Tax and health and education cess)");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 371, -1, 33));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Divident from the profits");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 496, -1, 33));

        dop.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        dop.setPreferredSize(new java.awt.Dimension(106, 28));
        dop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dopActionPerformed(evt);
            }
        });
        dop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dopKeyReleased(evt);
            }
        });
        getContentPane().add(dop, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 498, 147, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOMESTIC COMPANY", "FOREGIN COMPANY" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 67, 312, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 611, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 137, 207, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tax/calculation/system/simple-light-green-textured-background-wooden-surface-78371013.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 900, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpActionPerformed

    private void cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cpKeyReleased
     String age = (String)jComboBox1.getSelectedItem();
        if(age=="DOMESTIC COMPANY")
   {jLabel17.setVisible(true);
     dop.setVisible(true);
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
float num3=0;
num3=Float.parseFloat(dop.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.312));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.3338));
}
else
    {gt.setText(""+((num1+num2)*.3494));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.20586));
}  
  else
{mat.setText(""+((num2)*.21548));
}
  ddt.setText(""+((num3)*.2056));
   }
 else  if(age=="FOREGIN COMPANY")
   { 
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.4160));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.4243));
}
else
    {gt.setText(""+((num1+num2)*.4368));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.1962));
}  
  else
{mat.setText(""+((num2)*.20202));
}
  ddt.setText("Nil");
   }
// TODO add your handling code here
    }//GEN-LAST:event_cpKeyReleased

    private void gtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gtActionPerformed

    private void matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matActionPerformed

    private void ddtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddtActionPerformed

    private void dopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dopActionPerformed
        // TODO add your handling codeif((num2)<=10000000)

    }//GEN-LAST:event_dopActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 
       String age = (String)jComboBox1.getSelectedItem();
        if(age=="DOMESTIC COMPANY")
   {jLabel17.setVisible(true);
     dop.setVisible(true);}
     else  if(age=="FOREGIN COMPANY")
   { jLabel17.setVisible(false);
     dop.setVisible(false);
   }
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void pKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pKeyReleased
String age = (String)jComboBox1.getSelectedItem();
        if(age=="DOMESTIC COMPANY")
   {jLabel17.setVisible(true);
     dop.setVisible(true);
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
float num3=0;
num3=Float.parseFloat(dop.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.312));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.3338));
}
else
    {gt.setText(""+((num1+num2)*.3494));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.20586));
}  
  else
{mat.setText(""+((num2)*.21548));
}
  ddt.setText(""+((num3)*.2056));
   }
 else  if(age=="FOREGIN COMPANY")
   { 
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.4160));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.4243));
}
else
    {gt.setText(""+((num1+num2)*.4368));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.1962));
}  
  else
{mat.setText(""+((num2)*.20202));
}
  ddt.setText("Nil");
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_pKeyReleased

    private void dopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dopKeyReleased
String age = (String)jComboBox1.getSelectedItem();
        if(age=="DOMESTIC COMPANY")
   {jLabel17.setVisible(true);
     dop.setVisible(true);
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
float num3=0;
num3=Float.parseFloat(dop.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.312));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.3338));
}
else
    {gt.setText(""+((num1+num2)*.3494));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.20586));
}  
  else
{mat.setText(""+((num2)*.21548));
}
  ddt.setText(""+((num3)*.2056));
   }
 else  if(age=="FOREGIN COMPANY")
   { 
        float num1=0;
      num1=Float.parseFloat(cp.getText());
float num2=0;
num2=Float.parseFloat(p.getText());
if((num1+num2)<=10000000)
{gt.setText(""+((num1+num2)*.4160));
}
else if((num1+num2)>=10000001 && (num1+num2)<=100000000 )
{gt.setText(""+((num1+num2)*.4243));
}
else
    {gt.setText(""+((num1+num2)*.4368));
}
  if((num2)<=10000000)
{mat.setText(""+((num2)*.1924));
}   
else if((num2)>=10000001 && (num2)<=100000000 )
{mat.setText(""+((num2)*.1962));
}  
  else
{mat.setText(""+((num2)*.20202));
}
  ddt.setText("Nil");
   }
        // TODO add your handling code here:
    }//GEN-LAST:event_dopKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField1.setText("");
jTextField8.setText("");
jTextField2.setText("");
jTextField6.setText("");
jTextField4.setText("");
jTextField7.setText("");
cp.setText("");
p.setText("");
gt.setText("");
mat.setText("");
dop.setText("");
ddt.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(co_orperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(co_orperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(co_orperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(co_orperative.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new co_orperative().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cp;
    private javax.swing.JTextField ddt;
    private javax.swing.JTextField dop;
    private javax.swing.JTextField gt;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField mat;
    private javax.swing.JTextField p;
    // End of variables declaration//GEN-END:variables
}
