/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tax.calculation.system;

/**
 *
 * @author ADMIN
 */
public class gstform extends javax.swing.JFrame {

    /**
     * Creates new form gstform
     */
    public gstform() {
        initComponents();
        gstform:jComboBox1.setVisible(false);
        gstform:jComboBox2.setVisible(false);
        gstform:jComboBox3.setVisible(false);
        gstform:jComboBox4.setVisible(false);
        gstform:jComboBox5.setVisible(false);
        gstform:jComboBox6.setVisible(false);
        gstform:jComboBox7.setVisible(false);
        gstform:jComboBox8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pp = new javax.swing.JTextField();
        qt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        gst = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        fp = new javax.swing.JTextField();
        jComboBox8 = new javax.swing.JComboBox<>();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Good And Service Tax");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 19, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOVIE TICKETS", "CABLE AND DTH SERVICES", "SPORTING EVENTS " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 78, 311, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AYURVEDIC", "HOMEOPATHIC", "ALLOPATHIC", "UNANI" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 138, 311, -1));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIBER OR PLY WOOD", "WOODEN FURNITURE AND DECORATES", "OTHERS" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 204, 311, -1));

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAPER BASED", "BASE METALS", "PENS,PENCIL,ETC" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 269, 311, -1));

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "READYMADE CLOTHES", "CURTAINS,BEDSHEETS ETC", "RAW MATERIAL(COTTON,SILK,WOOL)" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 327, 311, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 397, -1, -1));

        jComboBox6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC(Food)", "NON AC(Food)", "ROOM SERVICE", " " }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 398, 311, -1));

        jComboBox7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SMALL CARS(Under 1200cc)", "MID-SIZE CARS(1200cc-1500CC)", "LUXURY CARS(Above 1500cc)", " " }));
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 452, 311, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("MEDIA AND ENTERTAINMENT");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 77, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("PRODUCT ORIGINAL PRICE");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 178, -1, -1));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 236, -1, -1));

        pp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppActionPerformed(evt);
            }
        });
        pp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ppKeyReleased(evt);
            }
        });
        getContentPane().add(pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 176, 99, -1));

        qt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        qt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        qt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtActionPerformed(evt);
            }
        });
        qt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                qtKeyReleased(evt);
            }
        });
        getContentPane().add(qt, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 236, 99, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("QUANTITY");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 238, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("TOTAL GST");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 321, -1, -1));

        gst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gst.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        gst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstActionPerformed(evt);
            }
        });
        getContentPane().add(gst, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 319, 99, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("FINAL PRICE");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 392, -1, -1));

        fp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        fp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fpActionPerformed(evt);
            }
        });
        getContentPane().add(fp, new org.netbeans.lib.awtextra.AbsoluteConstraints(895, 390, 99, -1));

        jComboBox8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELECTRIC MOTORS", "SEWING MACHINES", "BOILERS", "FIRE EXTINGUISHERS", " " }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 515, 311, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("MEDICINES");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 137, -1, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setText("FURNITURE");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 203, -1, -1));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton4.setText("STATIONERY");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 268, -1, -1));

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton5.setText("TEXTILE PRODUCTS");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 326, -1, -1));

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton6.setText("RESTRURANT");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 397, -1, -1));

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton7.setText("AUTOMOBILE");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 451, -1, -1));

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton8.setText("ELECTRONIC");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 514, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 563, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tax/calculation/system/images (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1010, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 String age = (String)jComboBox1.getSelectedItem();
 if(age=="MOVIE TICKETS")
{

pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
   
}
else if(age=="CABLE AND DTH SERVICES")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age=="SPORTING EVENTS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
String age4 = (String)jComboBox5.getSelectedItem();
if(age4=="READYMADE CLOTHES")
{
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age4=="CURTAINS,BEDSHEETS ETC")
{
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age4=="RAW MATERIAL(COTTON,SILK,WOOL)")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}      
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void fpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fpActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
        jComboBox1.setVisible(false);  
jComboBox2.setVisible(true);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false);

      // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);

jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false);
        jComboBox4.setVisible(true);  
 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);

jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false);
jComboBox5.setVisible(true);  
 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);

jComboBox8.setVisible(false);
jComboBox7.setVisible(true);  
 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
        jComboBox1.setVisible(true);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(true);        
       
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void gstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gstActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(true);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false);

 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);

jComboBox7.setVisible(false);
jComboBox8.setVisible(false);
jComboBox6.setVisible(true);    
 // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void ppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppKeyReleased
String age = (String)jComboBox1.getSelectedItem();
String age1 = (String)jComboBox2.getSelectedItem();
String age2 = (String)jComboBox3.getSelectedItem();
String age3 = (String)jComboBox4.getSelectedItem();
String age4 = (String)jComboBox5.getSelectedItem();
String age5 = (String)jComboBox6.getSelectedItem();
String age6 = (String)jComboBox7.getSelectedItem();
String age7 = (String)jComboBox8.getSelectedItem();
float num1=Float.parseFloat(pp.getText());
float num2=Float.parseFloat(qt.getText());
float num3=0;
if(age=="MOVIE TICKETS")
{
if(num1<=100)
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age=="CABLE AND DTH SERVICES")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age=="SPORTING EVENTS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="AYURVEDIC")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));}
else if(age1=="HOMEOPATHIC")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="ALLOPATHIC")
{num3=(float) ((num1*num2)*0.00);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="UNANI")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="FIBER OR PLY WOOD")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="WOODEN FURNITURE AND DECORATES")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="OTHERS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="PAPER BASED")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="BASE METALS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="PENS,PENCIL,ETC")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age4=="READYMADE CLOTHES")
{
    if(num1<=1000)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age4=="CURTAINS,BEDSHEETS ETC")
{
if(num1<=1000)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age4=="RAW MATERIAL(COTTON,SILK,WOOL)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="AC(Food)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="NON AC(Food)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="ROOM SERVICE")
{
    if(num1<=7500)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age6=="SMALL CARS(Under 1200cc)")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age6=="MID-SIZE CARS(1200cc-1500CC)")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age6=="LUXURY CARS(Above 1500cc)")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="ELECTRIC MOTORS")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="SEWING MACHINES")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="BOILERS")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="FIRE EXTINGUISHERS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
// TODO add your handling code here:
    }//GEN-LAST:event_ppKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jComboBox1.setVisible(false);  
jComboBox2.setVisible(false);
jComboBox3.setVisible(false);
jComboBox4.setVisible(false);
jComboBox5.setVisible(false);
jComboBox6.setVisible(false);
jComboBox7.setVisible(false);
jComboBox8.setVisible(false); 
jRadioButton1.setSelected(false);
jRadioButton2.setSelected(false);
jRadioButton3.setSelected(false);
jRadioButton4.setSelected(false);
jRadioButton5.setSelected(false);
jRadioButton6.setSelected(false);
jRadioButton7.setSelected(false);
jRadioButton8.setSelected(false);
pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtActionPerformed

    private void qtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtKeyReleased
      String age = (String)jComboBox1.getSelectedItem();
String age1 = (String)jComboBox2.getSelectedItem();
String age2 = (String)jComboBox3.getSelectedItem();
String age3 = (String)jComboBox4.getSelectedItem();
String age4 = (String)jComboBox5.getSelectedItem();
String age5 = (String)jComboBox6.getSelectedItem();
String age6 = (String)jComboBox7.getSelectedItem();
String age7 = (String)jComboBox8.getSelectedItem();
float num1=Float.parseFloat(pp.getText());
float num2=Float.parseFloat(qt.getText());
float num3=0;
if(age=="MOVIE TICKETS")
{
if(num1<=100)
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age=="CABLE AND DTH SERVICES")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age=="SPORTING EVENTS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="AYURVEDIC")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));}
else if(age1=="HOMEOPATHIC")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="ALLOPATHIC")
{num3=(float) ((num1*num2)*0.00);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age1=="UNANI")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="FIBER OR PLY WOOD")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="WOODEN FURNITURE AND DECORATES")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age2=="OTHERS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="PAPER BASED")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="BASE METALS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age3=="PENS,PENCIL,ETC")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age4=="READYMADE CLOTHES")
{
    if(num1<=1000)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age4=="CURTAINS,BEDSHEETS ETC")
{
if(num1<=1000)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age4=="RAW MATERIAL(COTTON,SILK,WOOL)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="AC(Food)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="NON AC(Food)")
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age5=="ROOM SERVICE")
{
    if(num1<=7500)
{num3=(float) ((num1*num2)*0.05);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}else
 {num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}   
}
else if(age6=="SMALL CARS(Under 1200cc)")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age6=="MID-SIZE CARS(1200cc-1500CC)")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age6=="LUXURY CARS(Above 1500cc)")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="ELECTRIC MOTORS")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="SEWING MACHINES")
{num3=(float) ((num1*num2)*0.12);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="BOILERS")
{num3=(float) ((num1*num2)*0.18);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
else if(age7=="FIRE EXTINGUISHERS")
{num3=(float) ((num1*num2)*0.28);
 gst.setText(""+num3);
 fp.setText(""+((num1*num2)+num3));
}
// TODO add your handling code here:
    }//GEN-LAST:event_qtKeyReleased

    private void ppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ppActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
String age1 = (String)jComboBox2.getSelectedItem();
        if(age1=="AYURVEDIC")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");}
else if(age1=="HOMEOPATHIC")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age1=="ALLOPATHIC")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age1=="UNANI")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
String age2 = (String)jComboBox3.getSelectedItem();   
if(age2=="FIBER OR PLY WOOD")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age2=="WOODEN FURNITURE AND DECORATES")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age2=="OTHERS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
String age3 = (String)jComboBox5.getSelectedItem();
     if(age3=="PAPER BASED")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age3=="BASE METALS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age3=="PENS,PENCIL,ETC")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
String age5 = (String)jComboBox5.getSelectedItem();
     // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
String age6 = (String)jComboBox5.getSelectedItem();
        if(age6=="SMALL CARS(Under 1200cc)")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age6=="MID-SIZE CARS(1200cc-1500CC)")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age6=="LUXURY CARS(Above 1500cc)")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
String age7 = (String)jComboBox8.getSelectedItem();       
if(age7=="ELECTRIC MOTORS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age7=="SEWING MACHINES")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age7=="BOILERS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
}
else if(age7=="FIRE EXTINGUISHERS")
{pp.setText("");
qt.setText("");
gst.setText("");
fp.setText("");
// TODO add your handling code here:
}
    }//GEN-LAST:event_jComboBox8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gstform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gstform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gstform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gstform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gstform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fp;
    private javax.swing.JTextField gst;
    private javax.swing.JButton jButton1;
    private static javax.swing.JComboBox<String> jComboBox1;
    private static javax.swing.JComboBox<String> jComboBox2;
    private static javax.swing.JComboBox<String> jComboBox3;
    private static javax.swing.JComboBox<String> jComboBox4;
    private static javax.swing.JComboBox<String> jComboBox5;
    private static javax.swing.JComboBox<String> jComboBox6;
    private static javax.swing.JComboBox<String> jComboBox7;
    private static javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField qt;
    // End of variables declaration//GEN-END:variables
}
