/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tax.calculation.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Divyasnhu Jain
 *
 */
public class tax_calculation extends javax.swing.JFrame {

    /**
     * Creates new form tax_calculation
     */
    
    public tax_calculation() { 
        initComponents();
 
               tax_calcultion:jLabel15.setVisible(false);
               tax_calcultion:jLabel16.setVisible(false);
               tax_calcultion:hra.setVisible(false);
               tax_calcultion:hrad.setVisible(false);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        remaningincome = new javax.swing.JTextField();
        taxcal = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        annual = new javax.swing.JTextField();
        annual1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        otherdeduct = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        edu = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        totaltax = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        hra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        hrad = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        totaldeduct = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Below 60 years", "60-80 years", "Above 80 years" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(781, 210, 104, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Remaning Annual Income ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 450, -1, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tax Calculated ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 484, -1, 33));

        remaningincome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        remaningincome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        remaningincome.setPreferredSize(new java.awt.Dimension(106, 28));
        remaningincome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                remaningincomeInputMethodTextChanged(evt);
            }
        });
        remaningincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remaningincomeActionPerformed(evt);
            }
        });
        remaningincome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                remaningincomeKeyReleased(evt);
            }
        });
        jPanel1.add(remaningincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 450, -1, -1));

        taxcal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        taxcal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        taxcal.setPreferredSize(new java.awt.Dimension(106, 28));
        taxcal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxcalActionPerformed(evt);
            }
        });
        jPanel1.add(taxcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 486, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 636, 104, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Annual Income");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 232, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 84, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Department");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 166, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Source of Income");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 124, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 131, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Pan no.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 87, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Bank A/C No.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 175, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 128, 207, -1));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 85, 207, -1));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 164, 207, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Other Income");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 265, -1, -1));

        annual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        annual.setText("0");
        annual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        annual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annualActionPerformed(evt);
            }
        });
        annual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                annualKeyReleased(evt);
            }
        });
        jPanel1.add(annual, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 229, 106, 28));

        annual1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        annual1.setText("0");
        annual1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        annual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annual1ActionPerformed(evt);
            }
        });
        annual1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                annual1KeyReleased(evt);
            }
        });
        jPanel1.add(annual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 263, 106, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Provident Fund");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 369, -1, -1));

        pf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pf.setText("0");
        pf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.add(pf, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 367, 106, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Other Deduction (LIC Polices, ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 307, -1, -1));

        otherdeduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otherdeduct.setText("0");
        otherdeduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        otherdeduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                otherdeductKeyReleased(evt);
            }
        });
        jPanel1.add(otherdeduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 307, 106, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Education Cess  and Health Cess(4%)");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 525, -1, -1));

        edu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        edu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        edu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eduActionPerformed(evt);
            }
        });
        jPanel1.add(edu, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 523, 106, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 173, 206, -1));

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 129, 206, -1));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 85, 206, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total Tax Calcuted");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 562, -1, -1));

        totaltax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totaltax.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        totaltax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltaxActionPerformed(evt);
            }
        });
        jPanel1.add(totaltax, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 560, 106, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("HRA Percentage");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 265, -1, -1));

        jComboBox2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resident", "Non Resident" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 235, -1, -1));

        hra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hra.setText("0");
        hra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        hra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hraActionPerformed(evt);
            }
        });
        hra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hraKeyReleased(evt);
            }
        });
        jPanel1.add(hra, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 263, 134, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("HRA Deducted");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 308, -1, -1));

        hrad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hrad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        hrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hradActionPerformed(evt);
            }
        });
        jPanel1.add(hrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 306, 134, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Medical Insurence)");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 339, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Total Deduction");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 406, -1, -1));

        totaldeduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totaldeduct.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        totaldeduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaldeductActionPerformed(evt);
            }
        });
        jPanel1.add(totaldeduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 404, 106, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel19.setText("Income Tax");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 11, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tax/calculation/system/download.jpg"))); // NOI18N
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1000, 680));

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totaldeductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaldeductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaldeductActionPerformed

    private void hradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hradActionPerformed

    private void hraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hraKeyReleased
        String age = (String)jComboBox1.getSelectedItem();

        if(age=="Below 60 years")
        {
            float num5 = 0;
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num3+num4)*0.12);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);

            pf.setText(""+num5);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=250000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=250001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 12500+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 112500+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }
        else
        if(age=="60-80 years")
        {float num3=0,num4=0;
            num4=Float.parseFloat(annual.getText());
            num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=300000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=300001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 10000+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 110000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else
            {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}

        }else
        if(age=="Above 80 years")
        {
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+(float)num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {

                float num1=num3+num4-num5-num6;

                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=500000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = (num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 100000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }     else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }          // TODO add your handling code here:
    }//GEN-LAST:event_hraKeyReleased

    private void hraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hraActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String house= (String)jComboBox2.getSelectedItem();
        if(house=="Non Resident")
        {jLabel15.setVisible(true);
            jLabel16.setVisible(true);
            hra.setVisible(true);
            hrad.setVisible(true);}
        else
        {jLabel15.setVisible(false);
            jLabel16.setVisible(false);
            hra.setVisible(false);
            hrad.setVisible(false);}
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void totaltaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltaxActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void eduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eduActionPerformed

    private void otherdeductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherdeductKeyReleased
        String age = (String)jComboBox1.getSelectedItem();

        if(age=="Below 60 years")
        {
            float num5 = 0;
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num3+num4)*0.12);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);

            pf.setText(""+num5);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=250000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=250001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 12500+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 112500+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }
        else
        if(age=="60-80 years")
        {float num3=0,num4=0;
            num4=Float.parseFloat(annual.getText());
            num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=300000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=300001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 10000+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 110000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else
            {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}

        }else
        if(age=="Above 80 years")
        {
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+(float)num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {

                float num1=num3+num4-num5-num6;

                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=500000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = (num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 100000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }     else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }          // TODO add your handling code here:
    }//GEN-LAST:event_otherdeductKeyReleased

    private void annual1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annual1KeyReleased
        String age = (String)jComboBox1.getSelectedItem();

        if(age=="Below 60 years")
        {
            float num5 = 0;
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num3+num4)*0.12);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);

            pf.setText(""+num5);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=250000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=250001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 12500+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 112500+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }
        else
        if(age=="60-80 years")
        {float num3=0,num4=0;
            num4=Float.parseFloat(annual.getText());
            num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=300000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=300001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 10000+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 110000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else
            {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}

        }else
        if(age=="Above 80 years")
        {
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+(float)num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {

                float num1=num3+num4-num5-num6;

                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=500000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = (num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 100000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }     else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }   // TODO add your handling code here:

    }//GEN-LAST:event_annual1KeyReleased

    private void annual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annual1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_annual1ActionPerformed

    private void annualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annualKeyReleased
        // TODO add your handling code here:
        String age = (String)jComboBox1.getSelectedItem();

        if(age=="Below 60 years")
        {
            float num5 = 0;
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num3+num4)*0.12);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);

            pf.setText(""+num5);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=250000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=250001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 12500+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 112500+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }
        else
        if(age=="60-80 years")
        {float num3=0,num4=0;
            num4=Float.parseFloat(annual.getText());
            num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {
                float num1=num3+num4-num5-num6;
                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=300000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=300001 && num1<=500000)
                {
                    float num2;
                    num2 = (num1*5)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = 10000+(num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 110000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }else
            {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}

        }else
        if(age=="Above 80 years")
        {
            float num4=Float.parseFloat(annual.getText());
            float num3=Float.parseFloat(annual1.getText());
            float num5=0;
            float num6=0;
            num6=Float.parseFloat(hra.getText());
            num6=((num6/100)*(num4+num3));
            float num7=Float.parseFloat(otherdeduct.getText());
            float num8=0;
            num5=(float)((num4+num3)*0.12);
            pf.setText(""+(float)num5);
            num8=num5+num7+num6;
            totaldeduct.setText(""+num8);
            if(num8<=150000)
            {

                float num1=num3+num4-num5-num6;

                remaningincome.setText(""+num1);
                hrad.setText(""+(float)num6);
                if(num1<=500000)
                {
                    String num2 ="Nill";
                    taxcal.setText(""+num2);
                }else if(num1>=500001 && num1<=1000000)
                {
                    float num2;
                    num2 = (num1*20)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }else
                {
                    float num2;
                    num2 = 100000+(num1*30)/100;
                    taxcal.setText(""+num2);
                    edu.setText(""+(float)(num2*0.04));
                    totaltax.setText(""+(float)(num2+(num2*0.04)));
                }
            }     else {JOptionPane.showMessageDialog(null,"Deduction should not be greater than 150000","Deduction Error",JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_annualKeyReleased

    private void annualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annualActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        annual.setText(""+0);
        annual1.setText(""+0);
        pf.setText(""+0);
        otherdeduct.setText(""+0);
        remaningincome.setText(null);
        taxcal.setText(null);
        edu.setText(null);
        jTextField3.setText(null);
        hra.setText("");
        hrad.setText(null);
        totaldeduct.setText(null);
        jTextField4.setText(null);
        jTextField2.setText(null);
        jTextField7.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        totaltax.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void taxcalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxcalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxcalActionPerformed

    private void remaningincomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_remaningincomeKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_remaningincomeKeyReleased

    private void remaningincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remaningincomeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_remaningincomeActionPerformed

    private void remaningincomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_remaningincomeInputMethodTextChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_remaningincomeInputMethodTextChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String age = (String)jComboBox1.getSelectedItem();
        if(age=="Below 60 years")
        {annual1.setText(""+0);
            annual.setText(""+0);
            pf.setText(""+0);
            otherdeduct.setText(""+0);
            totaldeduct.setText("");
            remaningincome.setText("");
            taxcal.setText("");
            edu.setText("");
            totaltax.setText("");
            hra.setText(""+0);
            hrad.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");}
        else if(age=="60-80 years")
        {annual1.setText(""+0);
            annual.setText(""+0);
            pf.setText(""+0);
            otherdeduct.setText(""+0);
            totaldeduct.setText("");
            remaningincome.setText("");
            taxcal.setText("");
            edu.setText("");
            totaltax.setText("");
            hra.setText(""+0);
            hrad.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");}
        else   {annual1.setText(""+0);
            annual.setText(""+0);
            pf.setText(""+0);
            otherdeduct.setText(""+0);
            totaldeduct.setText("");
            remaningincome.setText("");
            taxcal.setText("");
            edu.setText("");
            totaltax.setText("");
            hra.setText(""+0);
            hrad.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");}
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                 break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tax_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tax_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tax_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tax_calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           new tax_calculation().setVisible(true);
          }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annual;
    private javax.swing.JTextField annual1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField edu;
    private static javax.swing.JTextField hra;
    private static javax.swing.JTextField hrad;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private static javax.swing.JLabel jLabel15;
    private static javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField otherdeduct;
    private javax.swing.JTextField pf;
    private javax.swing.JTextField remaningincome;
    private javax.swing.JTextField taxcal;
    private javax.swing.JTextField totaldeduct;
    private javax.swing.JTextField totaltax;
    // End of variables declaration//GEN-END:variables

    void close(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void exit(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setVisible() {
         throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
